# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lGnW9zdxeOZ4b3tiQUe2Dblq2VR9GAgQ
"""

curl -k -o GSE13159_RAW.tar "https://94.124.179.195:9000/poly-bio-data/GSE13159_RAW.tar"